# Generated by Django 5.2.8 on 2025-12-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_service_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryshop',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
