# Generated by Django 5.2.7 on 2025-12-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_servicerating_shoprating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
