# Generated by Django 5.2.9 on 2025-12-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delay_notified',
            field=models.BooleanField(default=False),
        ),
    ]
