# Generated by Django 5.2.9 on 2025-12-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_delay_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='thank_you_sent',
            field=models.BooleanField(default=False),
        ),
    ]
