# Generated by Django 5.2.9 on 2025-12-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_thank_you_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryshop',
            name='razorpay_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
