# Generated by Django 5.2.7 on 2025-12-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_laundryshop_razorpay_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform commission amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, help_text='Razorpay order ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, help_text='Razorpay payment ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shop_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount to be transferred to shop', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='transfer_id',
            field=models.CharField(blank=True, help_text='Razorpay transfer ID to shop', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transfer_status',
            field=models.CharField(default='Pending', help_text='Status of transfer to shop', max_length=50),
        ),
    ]
