# Generated by Django 5.2.7 on 2025-12-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_platform_commission_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryshop',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, help_text='Account holder name as per bank records', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laundryshop',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laundryshop',
            name='bank_account_type',
            field=models.CharField(blank=True, choices=[('Savings', 'Savings'), ('Current', 'Current')], help_text='Type of bank account', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='laundryshop',
            name='bank_branch',
            field=models.CharField(blank=True, help_text='Bank branch name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laundryshop',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, help_text='IFSC code (e.g., HDFC0001234)', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='laundryshop',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name (e.g., HDFC Bank, SBI)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laundryshop',
            name='razorpay_account_id',
            field=models.CharField(blank=True, help_text='Razorpay Account ID for marketplace payments', max_length=100, null=True),
        ),
    ]
