# Generated by Django 5.2.7 on 2025-12-19 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_cloth'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cloths',
            field=models.ManyToManyField(blank=True, related_name='services', to='shop.cloth'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cloth')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.service')),
            ],
        ),
    ]
