# Generated by Django 5.2.7 on 2025-12-19 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_service_cloths_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceClothPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this cloth type in this service', max_digits=10)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='shop.cloth')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloth_prices', to='shop.service')),
            ],
            options={
                'unique_together': {('service', 'cloth')},
            },
        ),
    ]
