# Generated by Django 5.2.7 on 2025-12-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_serviceclothprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryshop',
            name='razorpay_key_id',
            field=models.CharField(blank=True, help_text='Razorpay Key ID for shop payments', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laundryshop',
            name='razorpay_key_secret',
            field=models.CharField(blank=True, help_text='Razorpay Key Secret for shop payments', max_length=100, null=True),
        ),
    ]
