# Generated by Django 5.2.7 on 2025-12-24 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_laundryshop_razorpay_key_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchCloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_cloths', to='shop.branch')),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_availability', to='shop.cloth')),
            ],
            options={
                'unique_together': {('branch', 'cloth')},
            },
        ),
    ]
