# Generated by Django 5.2.9 on 2026-01-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_branchcloth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='platform_commission',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shop_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transfer_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transfer_status',
        ),
        migrations.AddField(
            model_name='order',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Final payable amount (base + fees + GST)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
