# Generated by Django 5.2.9 on 2026-01-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_order_platform_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cloth_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Pickup', 'Pickup'), ('Washing', 'Washing'), ('Drying', 'Drying'), ('Ironing', 'Ironing'), ('Ready', 'Ready for Pickup'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
