# Generated by Django 5.2.9 on 2026-01-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_auto_saved',
            field=models.BooleanField(default=False),
        ),
    ]
