# Generated by Django 5.2.9 on 2026-01-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_profile_location_auto_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location_auto_saved',
        ),
    ]
