# Generated by Django 5.2.9 on 2026-01-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_profile_location_auto_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
