# Generated by Django 5.2.9 on 2026-01-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_branch_unique_together_branch_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='predicted_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
