# Generated by Django 5.2.9 on 2026-01-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_order_predicted_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='base_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delay_notified',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='gst_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='platform_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='thank_you_sent',
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
