# Generated by Django 5.2.9 on 2026-01-07 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_order_base_amount_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_temperature', models.CharField(max_length=50)),
                ('wash_cycle', models.CharField(max_length=50)),
                ('detergent', models.CharField(max_length=50)),
                ('drying_method', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wash_recommendation', to='shop.orderitem')),
            ],
        ),
    ]
