# Generated by Django 5.2.9 on 2026-01-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_washrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='overdue_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
