# Generated by Django 5.2.9 on 2026-01-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_notification_shop_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
