# Generated by Django 5.2.9 on 2026-01-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_order_last_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopnotification',
            name='notification_type',
            field=models.CharField(default='info', max_length=50),
        ),
        migrations.AlterField(
            model_name='shopnotification',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shopnotification',
            name='icon',
            field=models.CharField(max_length=50),
        ),
    ]
