# Generated by Django 5.2.9 on 2026-01-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_shopnotification_notification_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopnotification',
            name='notification_type',
        ),
        migrations.AlterField(
            model_name='shopnotification',
            name='color',
            field=models.CharField(default='#e74c3c', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopnotification',
            name='icon',
            field=models.CharField(default='fas fa-exclamation-triangle', max_length=50),
        ),
    ]
