# Generated by Django 5.2.9 on 2026-02-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_remove_shopnotification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoprating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shoprating',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shoprating',
            name='user',
        ),
        migrations.DeleteModel(
            name='BranchRating',
        ),
        migrations.DeleteModel(
            name='ShopRating',
        ),
    ]
