# Generated by Django 5.2.9 on 2026-02-24 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_shoprating_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicerating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='servicerating',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.branch'),
        ),
        migrations.AddField(
            model_name='servicerating',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.laundryshop'),
        ),
        migrations.AlterField(
            model_name='servicerating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicerating',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='servicerating',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.service'),
        ),
    ]
