# Generated by Django 5.2.9 on 2026-02-25 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_alter_servicerating_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='servicerating',
            constraint=models.UniqueConstraint(fields=('user', 'shop'), name='unique_user_shop_rating'),
        ),
        migrations.AddConstraint(
            model_name='servicerating',
            constraint=models.UniqueConstraint(fields=('user', 'service'), name='unique_user_service_rating'),
        ),
    ]
